stages:
- prepare
- test
- build
- release


default:
  tags:
    - docker


variables:
  # docker images for test services
  TESTS_IMAGE_REGISTRY: 'registry:2.8.3'
  TESTS_IMAGE_POSTGIS: 'cytomine/postgis:1.4.0-dev.2'
  APPENGINE_TASKS_PATH: GitLab/Artifacts/AppEngine/Tasks
  ADD_INTEGER_TASK_NAME: com.cytomine.dummy.arithmetic.integer.addition-1.0.0.zip
  ADD_CONSTRAINED_INTEGER_TASK_NAME: com.cytomine.dummy.arithmetic.integer.addition.constrained-1.0.0.zip
  IDENTITY_BOOLEAN_TASK_NAME: com.cytomine.dummy.identity.boolean-1.0.0.zip
  IDENTITY_ENUMERATION_TASK_NAME: com.cytomine.dummy.identity.enumeration-1.0.0.zip
  IDENTITY_NUMBER_TASK_NAME: com.cytomine.dummy.identity.number-1.0.0.zip
  IDENTITY_STRING_TASK_NAME: com.cytomine.dummy.identity.string-1.0.0.zip
  IDENTITY_GEOMETRY_TASK_NAME: com.cytomine.dummy.identity.geometry-1.0.0.zip
  IDENTITY_IMAGE_TASK_NAME: com.cytomine.dummy.identity.image-1.0.0.zip
  SUB_INTEGER_TASK_NAME: com.cytomine.dummy.arithmetic.integer.subtraction-1.0.0.zip
  TEST_ARTIFACT_PATH: ./src/test/resources/artifacts


include:
  # download tasks
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${ADD_INTEGER_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-integer-addition
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${ADD_CONSTRAINED_INTEGER_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-constrained-integer-addition
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${IDENTITY_BOOLEAN_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-boolean-identity
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${IDENTITY_ENUMERATION_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-enumeration-identity
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${IDENTITY_NUMBER_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-number-identity
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${IDENTITY_STRING_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-string-identity
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${SUB_INTEGER_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-integer-subtraction
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${IDENTITY_GEOMETRY_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-geometry-identity
  - component: gitlab.cytom.in/cm/rnd/cicd/component-nextcloud/download-file@1.1.0
    inputs:
      source-filepath: ${APPENGINE_TASKS_PATH}/${IDENTITY_IMAGE_TASK_NAME}
      target-directory: ${TEST_ARTIFACT_PATH}
      job-name: download-task-image-identity

  - component: $CI_SERVER_FQDN/cm/rnd/cicd/component-docker/build-docker-image@2.0.0
    inputs:
      docker-image-name: ${CI_REGISTRY_IMAGE}
      dockerfile-path: docker/Dockerfile
  - component: $CI_SERVER_FQDN/cm/rnd/cicd/component-docker/push-image-to-registry@2.0.0
    inputs:
      push-latest-tag: "true"


download-task-integer-addition:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${ADD_INTEGER_TASK_NAME}


download-task-constrained-integer-addition:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${ADD_CONSTRAINED_INTEGER_TASK_NAME}


download-task-boolean-identity:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${IDENTITY_BOOLEAN_TASK_NAME}


download-task-enumeration-identity:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${IDENTITY_ENUMERATION_TASK_NAME}


download-task-number-identity:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${IDENTITY_NUMBER_TASK_NAME}


download-task-string-identity:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${IDENTITY_STRING_TASK_NAME}

download-task-geometry-identity:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${IDENTITY_GEOMETRY_TASK_NAME}


download-task-image-identity:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${IDENTITY_IMAGE_TASK_NAME}


download-task-integer-subtraction:
  artifacts:
    paths:
      - ${TEST_ARTIFACT_PATH}/${SUB_INTEGER_TASK_NAME}


lint-dockerfiles:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/hadolint/hadolint:latest-alpine
  # Uncomment to silent some warnings if needed
  #variables:
  #  HADOLINT_OPT: --ignore DL3008
  script:
    - hadolint ${HADOLINT_OPT} docker/Dockerfile
  rules:
    - changes:
        - docker/Dockerfile
      when: always
    # If the Dockerfile has not been changed, this job can be skipped
    - when: never
      allow_failure: true


validate-descriptor-schema:
  stage: test
  tags:
    - docker
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:16-alpine3.18
  variables:
    SCHEMA_PATH: ./src/main/resources/schemas/tasks/task.v0.json
  script:
    - apk update && apk add jq
    # Install dependencies
    - npm install -g ajv-cli@5.0.0 ajv-formats@2.1.1 ajv-formats-draft2019@1.6.1
    # Extract the $schema value from schema.json
    - BASE_SCHEMA_URL=$(jq -r '.["$schema"]' ${SCHEMA_PATH})
    # Infer spec based on the extracted URL
    - |
      case "$BASE_SCHEMA_URL" in
        *draft-07*) SPEC="draft7";;
        *2019-09*) SPEC="draft2019";;
        *2020-12*) SPEC="draft2020";;
        *)
          echo "Unknown schema specification for URL: '$BASE_SCHEMA_URL'"
          echo "Aborting..."
          exit 1
        ;;
      esac
    # Run the ajv validate command with the determined spec
    - echo "Running validator with JSON Schema specification '${SPEC}'"
    - ajv compile -s ${SCHEMA_PATH} -c ajv-formats -c ajv-formats-draft2019 --spec=${SPEC} --strict=false --all-errors


validate-openapi-spec:
  stage: test
  tags:
    - docker
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/redocly/cli:1.10.6
    entrypoint: [""]
  variables:
    OPENAPI_PATH: src/test/resources/spec/api/openapi_spec.v0.1.0.yml
  script:
    - redocly lint ${OPENAPI_PATH}


tests-storage-registry:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/gradle:8.4-jdk17-alpine
  needs:
    - job: download-task-integer-addition
      artifacts: true
    - job: download-task-constrained-integer-addition
      artifacts: true
    - job: download-task-boolean-identity
      artifacts: true
    - job: download-task-enumeration-identity
      artifacts: true
    - job: download-task-number-identity
      artifacts: true
    - job: download-task-string-identity
      artifacts: true
    - job: download-task-geometry-identity
      artifacts: true
    - job: download-task-image-identity
      artifacts: true
    - job: download-task-integer-subtraction
      artifacts: true
  services:
    - alias: postgres
      name: $TESTS_IMAGE_POSTGIS
    - alias: registry
      name: $TESTS_IMAGE_REGISTRY
    # TODO
    # - alias: registry
    #   name: $TESTS_IMAGE_REGISTRY
  variables:
    # postgres db
    POSTGRES_DB: docker
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: password
    POSTGRES_PORT: 5432
    POSTGRES_USER: docker
    APPENGINE_DB: appengine
    APPENGINE_USER: appengine
    APPENGINE_PASSWORD: password
    # registry
    REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: '/data'
    REGISTRY_HOST: registry
    REGISTRY_PORT: 5000
    REGISTRY_SCHEME: http
    # app engine config
    DB_HOST: postgres
    DB_NAME: appengine
    DB_USERNAME: appengine
    DB_PASSWORD: password
  script:
    - gradle :test --no-daemon
  artifacts:
    when: always
    reports:
      junit: build/test-results/**/TEST-*.xml
      # TODO integrate code coverage
    paths:
      - build/reports/tests/cucumber/*.html

build-docker-image:
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    OPENJDK_VERSION: 17-slim-bullseye
    GRADLE_VERSION: 8.5.0-jdk17-alpine
    ENTRYPOINT_SCRIPTS_VERSION: 1.3.2
    DOCKER_TAG: ${CI_COMMIT_TAG}
  before_script:
    - ARGS="${ARGS} --build-arg APP_ENGINE_VERSION=${CI_COMMIT_TAG}"
    - ARGS="${ARGS} --build-arg APP_ENGINE_REVISION=${CI_COMMIT_SHORT_SHA}"
    - ARGS="${ARGS} --build-arg ENTRYPOINT_SCRIPTS_VERSION=${ENTRYPOINT_SCRIPTS_VERSION}"
    - ARGS="${ARGS} --build-arg GRADLE_VERSION=${GRADLE_VERSION}"
    - ARGS="${ARGS} --build-arg OPENJDK_VERSION=${OPENJDK_VERSION}"

push-image-to-registry:
  rules:
    - if: $CI_COMMIT_TAG

