server:
  tomcat:
    basedir: /tmp/appengine
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      max-file-size: 15GB
      max-request-size: 15GB
      location: /tmp/appengine/uploads
  datasource:
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appengine}
    username: ${DB_USERNAME:appengine}
  hibernate:
    ddl-auto: drop-create
    show-sql: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: classpath:master-changelog.yml
  security:
    basic:
      enabled: false
    ignored: ${API_PREFIX:/api/}\*\*
  management:
    security:
      enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
storage:
  base-path: ${STORAGE_BASE_PATH:/data}
  impl: ${STORAGE_IMPL:filesystem} # possible values [filesystem]
  input:
    charset: UTF_8 # possible values [UTF_8,US_ASCII,ISO_8859_1,UTF_16LE,UTF_16BE,UTF_16] and UTF_8 is default
registry:
  impl: ${REGISTRY_IMPL:docker} # possible values [docker.default]
  scheme: ${REGISTRY_HTTP_SCHEME:http}
  host: ${REGISTRY_URL:registry}:${REGISTRY_PORT:5000}
  url: ${registry.scheme:http}://${registry.host}
scheduler:
  impl: default # possible values [default]
  master-url: ${SCHEDULER_MASTER_URL:http://scheduler:16443}
  oauth-token: ${SCHEDULER_OAUTH_TOKEN:token}
  username: ${SCHEDULER_USERNAME:admin}
registry-client:
  authenticated: false
  user: user #ignored
  password: password #ignored
  host: ${REGISTRY_HOST:registry}
  port: ${REGISTRY_PORT:5000}
  scheme: ${REGISTRY_SCHEME:http}
logging:
  level:
    root: ERROR
    be.cytomine.appengine: INFO
app-engine:
  version: ce-0.0.0 # do not modify this, it will be replaced during build (ci)
  api_version: v1
  api_prefix: ${API_PREFIX:/api/}