name: CBIR

on:
  pull_request:
    branches:
      - main
    paths:
      - "cbir/**/*.py"
      - "cbir/tests/**"
      - ".github/**"
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./cbir

# Hardcoded for compatibility
env:
  PYTHON_VERSION: "3.10"

jobs:
  lint:
    if: false # Disable lint job by default, enable it manually if needed
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          working-directory: ./cbir

      - name: Lint
        run: poetry run pylint --output=lint.txt cbir tests

      - name: Upload lint report
        if: ${{ always() }}
        run: |
          echo '# Lint report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat lint.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  type-check:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          working-directory: ./cbir

      - name: Type check
        run: >-
          poetry run mypy
          --disallow-incomplete-defs
          --disallow-untyped-calls
          --disallow-untyped-defs
          --txt-report ./
          cbir tests

      - name: Upload type check coverage report
        if: ${{ always() }}
        run: |
          echo '# Type check coverage report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat index.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  test:
    runs-on: self-hosted

    services:
      redis:
        image: redis:${{ vars.REDIS_VERSION }}
        ports:
          - 6379:6379

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          working-directory: ./cbir

      - name: Run tests
        run: python -m poetry run coverage run -m pytest
        env:
          DATA_PATH: ./
          WEIGHTS: ./weights/resnet

      - name: Upload coverage report
        run: |
          echo '# Coverage report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          python -m poetry run coverage report -m >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
